language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

env:
  - UNCERTAINTIES="N" NUMPY_VERSION=0
  - UNCERTAINTIES="N" NUMPY_VERSION=1.6
  - UNCERTAINTIES="N" NUMPY_VERSION=1.7
  - UNCERTAINTIES="N" NUMPY_VERSION=1.8
  - UNCERTAINTIES="Y" NUMPY_VERSION=0
  - UNCERTAINTIES="Y" NUMPY_VERSION=1.6
  - UNCERTAINTIES="Y" NUMPY_VERSION=1.7
  - UNCERTAINTIES="Y" NUMPY_VERSION=1.8

branches:
  only:
    - master
    - develop

install: 
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - if [[ $UNCERTAINTIES == 'Y' ]]; then pip install uncertainties; fi
    - if [ $NUMPY_VERSION = '0' ]; then pip uninstall -y numpy || true; else pip install numpy==$NUMPY_VERSION; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python setup.py install; else pip install . ; fi
    - pip list --pre

script: python setup.py test

matrix:
    # Don't run with these version combinations as these NumPy packages don't seem to be installable with Travis
    exclude:
        - python: "3.2"
          env: UNCERTAINTIES="N" NUMPY_VERSION=1.6
        - python: "3.2"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=1.6
        - python: "3.3"
          env: UNCERTAINTIES="N" NUMPY_VERSION=1.6
        - python: "3.3"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=1.6
        - python: "pypy"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=1.6
        - python: "pypy"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=1.7
        - python: "pypy"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=1.8
        - python: "pypy"
          env: UNCERTAINTIES="N" NUMPY_VERSION=1.6
        - python: "pypy"
          env: UNCERTAINTIES="N" NUMPY_VERSION=1.7
        - python: "pypy"
          env: UNCERTAINTIES="N" NUMPY_VERSION=1.8
        - python: "pypy"
          env: UNCERTAINTIES="Y" NUMPY_VERSION=0
        - python: "pypy"
          env: UNCERTAINTIES="N" NUMPY_VERSION=0
